<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Work+Sans:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Tangerine:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/fontawesome.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/brands.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/solid.min.css"> 
    <link rel="stylesheet" href="../scss/style.css">
    <title>About</title>
</head>
<body>
    <header></header>
    <main>
        <div class="row mainDiv">
            <section class="about column">
                <img src="" alt="">
                <h1>Paul Bora Akcan</h1>
                <p>Developeur Web / Ecrivain</p>
                <div>
                    <a href="mailto:paulbora_akcan@hotmail.com"><i class="fas fa-envelope"></i>paulbora_akcan@hotmail.com</a>
                </div>
                <a href="https://github.com/Sixcha" target="_blank" class="fab fa-github fa-2x"></a>
                <p>Diplômée en langue et littérature Anglaise avec un rêve de créer des jeux vidéo. Je fais aussi de l'écriture créative. Actuellement en train d'apprendre le développement Web avant de se concentrer sur C# et Python.</p>
                <p>Ce portfolio sert de lieu pour tous mes projets personnels. Il sera mis à jour avec plus de catégories au fur et à mesure que ma carrière progresse.</p>
            </section>
            <div class="flexFix">
                <section id="ajax" class="column">
                    <div class="creationFix row" id="ajax2">
                    <article class="content">
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi qui a ad odit consequatur incidunt dolores neque maiores facilis earum, nemo quia porro ipsum nulla voluptas omnis vel quisquam vero cum quas nihil fuga. Ratione eos ex illo nihil nobis veniam dolorem eligendi esse mollitia sed accusamus earum vitae vero aspernatur molestias asperiores maiores facilis, ipsa quam inventore rem dolor odit modi! Ex ullam consectetur earum veniam rerum possimus, iste debitis nesciunt tenetur fugiat assumenda, nostrum deleniti. Tempora, iusto! Incidunt facilis odit dignissimos, nemo beatae quam possimus qui amet exercitationem reprehenderit voluptatibus saepe, pariatur necessitatibus in voluptatum? Totam, velit dolorem.</p>
                        <p>Atque consectetur nihil, magnam perspiciatis excepturi fuga odio nemo sequi, optio quia dicta eum suscipit odit sed quae quibusdam ipsam voluptates veritatis cum iusto distinctio. Explicabo saepe dolorem corrupti itaque! Amet, iure, nostrum impedit voluptates omnis sapiente veritatis nam cupiditate voluptas libero voluptatem corporis? Corporis rerum doloribus odio dolor, quasi sunt nisi nesciunt, numquam, consequuntur alias quos cupiditate quis? Voluptatem maiores magni magnam error itaque eaque ipsa illo iste officia ipsam deserunt impedit saepe facere doloremque possimus, cupiditate eum odit nobis rerum provident quasi enim cum commodi. Aspernatur incidunt tempore consequatur reiciendis? Nesciunt, nam aliquam. Consequuntur earum obcaecati esse repellendus.</p>
                        <p>Quas quis consectetur, repellat sed maxime dicta ipsa provident odio repudiandae beatae velit numquam consequatur veritatis porro sapiente ex quia a exercitationem non iste nulla laboriosam saepe dolore. Sit in nam numquam voluptates inventore! Expedita magni tenetur aperiam veniam ipsum labore doloremque eveniet enim minima, maxime autem ducimus sunt ratione at eaque, architecto aspernatur natus. Eius natus dolores, nostrum nesciunt magnam, debitis iusto sit quisquam maiores laudantium perspiciatis doloribus eaque dicta vitae voluptatum temporibus laboriosam, animi iste necessitatibus voluptates ad modi? Ullam tenetur omnis iusto fuga consequuntur autem repellendus enim ratione est soluta iste cumque magnam, nobis eius pariatur dolorum!</p>
                        <p>Ab, consectetur dicta alias necessitatibus quo consequuntur quam qui iure eveniet nobis blanditiis dolor doloremque voluptatem quisquam, cum numquam esse beatae error laborum porro, quis laudantium dolorem sapiente molestias! Cum blanditiis amet iure suscipit maiores minima laborum dicta voluptatem reprehenderit ut? Sit minus sunt itaque, omnis architecto tempora vero consequatur praesentium et ex, saepe mollitia. Fugiat fugit illum eum pariatur, rem officiis deleniti ea sint numquam nam, inventore doloribus asperiores earum soluta! Qui ipsa quia earum, suscipit iusto totam delectus vero? Eaque eveniet illo dolore cum aspernatur similique mollitia, esse alias perspiciatis rem corporis, repellendus distinctio quidem corrupti. Expedita, ut.</p>
                    </article>
                    </div>
                </section>
            </div>
            <div class="side column frfix">
                <a href="javascript:void(0);" onclick="showSide()" id="mobileFunc" class="langLink"><i id="faArrow" class="fas fa-angle-left fa-2x"></i></a>
                <a href="index.php?page=about&lang=eng" class="langLink hidden">Eng</a>
                <a href="index.php?page=about&lang=fr" class="selectedLang langLink hidden">Fr</a>
                <a href="#" class="langLink hidden">Retour en haut</a>
                <a href="index.php?page=home&lang=fr" class="hidden">Page D'acceuil</a>
            </div>
        </div>
    </main>
</body>
<script src="../js/utilities.js"></script>
</html>