<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Work+Sans:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Tangerine:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/fontawesome.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/brands.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/solid.min.css"> 
    <link rel="stylesheet" href="../scss/style.css">
    <title>About</title>
</head>
<body>
    <header></header>
    <main>
        <div class="row mainDiv">
            <section class="about column">
                <img src="" alt="">
                <h1>Paul Bora Akcan</h1>
                <p>Web Developper / Writer</p>
                <div>
                    <a href="mailto:paulbora_akcan@hotmail.com"><i class="fas fa-envelope"></i>paulbora_akcan@hotmail.com</a>
                </div>
                <a href="https://github.com/Sixcha" target="_blank" class="fab fa-github fa-2x"></a>
                <p>An English Language and Litterature graduate with a dream of making video games. I do creative writing as well. Currently learning Web Development before focusing on C# and Python.</p>
                <p>This portfolio serves as a place to hold all of my personal projects. It will be updated with more categories as my career progresses further.</p>
            </section>
            <div class="flexFix">
                <section id="ajax" class="column">
                    <div class="creationFix row" id="ajax2">
                    <article class="content">
                        <p>My name is Paul Bora Akcan. I am a full stack web developer with proficiency of HTML, CSS, Javascript, PHP and SQL as well as SCSS and Symfony.</p>
                        <p>As an English Litterature student, I also learned a lot about how to write stories, something I loved doing since I was a kid. I wish to use that skill to give life to video game worlds, another one of my passions.</p>
                        <p>I spend most of my time coding, playing and making games. I love to learn skills that can be useful to me, so you can find me growing my repertoire of knowledge as well.</p>
                    </article>
                    </div>
                </section>
            </div>
            <div class="side column">
                <a href="javascript:void(0);" onclick="showSide()" id="mobileFunc" class="langLink"><i id="faArrow" class="fas fa-angle-left fa-2x"></i></a>
                <a href="index.php?page=about&lang=eng" class="selectedLang langLink hidden">Eng</a>
                <a href="index.php?page=about&lang=fr" class="langLink hidden">Fr</a>
                <a href="#" class="langLink hidden">Back to Top</a>
                <a href="index.php" class="langLink hidden">Home Page</a>
            </div>
        </div>
    </main>
</body>
<script src="../js/utilities.js"></script>
</html>