<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Work+Sans:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Tangerine:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/fontawesome.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/brands.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/solid.min.css"> 
    <link rel="stylesheet" href="../scss/style.css">
    <title>About</title>
</head>
<body>
    <header></header>
    <main>
        <div class="row mainDiv">
            <section class="about column">
                <img src="" alt="">
                <h1>Paul Bora Akcan</h1>
                <p>Developeur Web / Ecrivain</p>
                <div>
                    <a href="mailto:paulbora_akcan@hotmail.com"><i class="fas fa-envelope"></i>paulbora_akcan@hotmail.com</a>
                </div>
                <a href="https://github.com/Sixcha" target="_blank" class="fab fa-github fa-2x"></a>
                <p>Diplômée en langue et littérature Anglaise avec un rêve de créer des jeux vidéo. Je fais aussi de l'écriture créative. Actuellement en train d'apprendre le développement Web avant de se concentrer sur C# et Python.</p>
                <p>Ce portfolio sert de lieu pour tous mes projets personnels. Il sera mis à jour avec plus de catégories au fur et à mesure que ma carrière progresse.</p>
            </section>
            <div class="flexFix">
                <section id="ajax" class="column">
                    <div class="creationFix row" id="ajax2">
                    <article class="content">
                        <p>Je m'appelle Paul Bora Akcan. Je suis un développeur web full stack maîtrisant HTML, CSS, Javascript, PHP et SQL ainsi que SCSS et Symfony.</p>
                        <p>En tant qu'étudiant en littérature anglaise, j'ai aussi beaucoup appris sur la façon d'écrire des histoires, quelque chose que j'aimais faire depuis que je suis enfant. Je souhaite utiliser cette compétence pour donner vie aux univers du jeu vidéo, une autre de mes passions.</p>
                        <p>Je passe la plupart de mon temps à coder, à jouer et à créer des jeux. J'aime acquérir des compétences qui peuvent m'être utiles, donc vous pouvez également me trouver en train d'élargir mon répertoire de connaissances.</p>
                    </article>
                    </div>
                </section>
            </div>
            <div class="side column frfix">
                <a href="javascript:void(0);" onclick="showSide()" id="mobileFunc" class="langLink"><i id="faArrow" class="fas fa-angle-left fa-2x"></i></a>
                <a href="index.php?page=about&lang=eng" class="langLink hidden">Eng</a>
                <a href="index.php?page=about&lang=fr" class="selectedLang langLink hidden">Fr</a>
                <a href="#" class="langLink hidden">Retour en haut</a>
                <a href="index.php?page=home&lang=fr" class="hidden">Page D'acceuil</a>
            </div>
        </div>
    </main>
</body>
<script src="../js/utilities.js"></script>
</html>