<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Work+Sans:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Tangerine:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/fontawesome.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/brands.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/solid.min.css"> 
    <link rel="stylesheet" href="../scss/style.css">
    <title>About</title>
</head>
<body>
    <header></header>
    <main>
        <div class="row mainDiv">
            <section class="about column">
                <img src="" alt="">
                <h1>Paul Bora Akcan</h1>
                <p>Web Developper / Writer</p>
                <div>
                    <a href="mailto:paulbora_akcan@hotmail.com"><i class="fas fa-envelope"></i>paulbora_akcan@hotmail.com</a>
                </div>
                <a href="https://github.com/Sixcha" target="_blank" class="fab fa-github fa-2x"></a>
                <p>An English Language and Litterature graduate with a dream of making video games. I do creative writing as well. Currently learning Web Development before focusing on C# and Python.</p>
                <p>This portfolio serves as a place to hold all of my personal projects. It will be updated with more categories as my career progresses further.</p>
            </section>
            <div class="flexFix">
                <section id="ajax" class="column">
                    <div class="creationFix row" id="ajax2">
                    <article class="content">
                        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Est omnis qui quo doloremque rem adipisci iste, voluptates dignissimos! Totam adipisci laborum quod, tenetur ullam vel officiis deleniti natus! Iusto, fugit repellat facere dolorem possimus expedita magnam delectus fugiat at. Consequuntur, itaque. Porro, alias ullam mollitia veniam commodi nesciunt officia consequatur accusantium hic deserunt officiis assumenda ad maxime sit harum totam possimus quo vero. Molestias sint nulla minus repudiandae assumenda dolor minima accusantium laudantium dolorem deserunt. Magnam aspernatur consectetur id hic, doloribus cumque, velit explicabo, dolor ullam cupiditate itaque temporibus vero tempora modi atque eaque laboriosam voluptatum praesentium a illum error.</p>
                        <p>Doloremque eveniet laborum nobis consequuntur, unde veniam ullam vel repellendus nostrum vero blanditiis commodi dignissimos amet. Illo consequatur architecto dolorum modi suscipit sapiente, assumenda nobis eos error! Consectetur ipsam nobis rem qui ea architecto nihil unde? Dolor minus, sequi possimus expedita esse hic accusantium cupiditate itaque quae, culpa provident explicabo quo ratione dolorem, repudiandae debitis! Consequatur voluptatibus laborum reiciendis quo nostrum alias repudiandae et, iusto rem minima. Veniam deserunt saepe corrupti, debitis numquam necessitatibus adipisci inventore voluptas neque excepturi incidunt exercitationem fugit ut voluptatibus omnis odio hic optio perferendis praesentium ea autem quasi. Facilis voluptatem similique eligendi vero, necessitatibus ipsam?</p>
                        <p>Quisquam atque neque, itaque suscipit, fuga necessitatibus enim odio sed rerum, omnis corporis nesciunt. Non ipsam sapiente placeat itaque culpa eaque, natus odit esse harum. Delectus enim quibusdam autem, nisi quos nobis suscipit! Fugiat, cupiditate neque non veniam velit facilis quaerat dolores saepe fuga recusandae? Sapiente, saepe? Voluptas eos nesciunt earum exercitationem. Earum, numquam. Laudantium cumque exercitationem voluptates, minus repudiandae veritatis, facere cum accusamus laboriosam neque maxime eius, tenetur consequuntur illum facilis corrupti molestias nostrum? Quaerat, voluptatem vitae? Molestias vero eius ea ipsam accusantium explicabo corrupti! Numquam officia provident, facere quae veniam dicta, sit dolor cum architecto soluta quam ipsam.</p>
                        <p>At minus pariatur ipsum suscipit cupiditate sapiente est in fugiat assumenda distinctio obcaecati voluptatum deserunt voluptatem illo, repellendus eius qui architecto corrupti natus! Veniam magni deleniti, nisi harum ea mollitia accusamus obcaecati, dolores magnam vero libero quo repellendus hic voluptates corrupti iste? Est iste id dolores itaque autem, architecto nisi, dicta esse eveniet commodi velit deleniti, dolore quis. Assumenda deleniti molestias, consequuntur rem soluta incidunt, illo consectetur recusandae odio sit error? Voluptatem temporibus, obcaecati adipisci voluptatibus inventore perspiciatis ipsam facilis ab, labore odio assumenda hic voluptates illo laboriosam doloribus maiores! Dicta veniam, nihil quae similique laudantium nam eveniet repudiandae ratione.</p>
                    </article>
                    </div>
                </section>
            </div>
            <div class="side column">
                <a href="javascript:void(0);" onclick="showSide()" id="mobileFunc" class="langLink"><i id="faArrow" class="fas fa-angle-left fa-2x"></i></a>
                <a href="index.php" class="selectedLang langLink hidden">Eng</a>
                <a href="index.php?page=about&lang=fr" class="langLink hidden">Fr</a>
                <a href="#" class="langLink hidden">Back to Top</a>
                <a href="index.php" class="langLink hidden">Home Page</a>
            </div>
        </div>
    </main>
</body>
<script src="../js/utilities.js"></script>
</html>