<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Work+Sans:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Tangerine:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/fontawesome.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/brands.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/solid.min.css"> 
    <link rel="stylesheet" href="scss/style.css">
    <title>Portfolio</title>
</head>
<body>
    <header>
    </header>
    <main>
        <div class="row mainDiv">
            <section class="about column">
                <img src="" alt="">
                <h1>Paul Bora Akcan</h1>
                <p>Web Developper / Writer</p>
                <div>
                    <a href="mailto:paulbora_akcan@hotmail.com"><i class="fas fa-envelope"></i>paulbora_akcan@hotmail.com</a>
                </div>
                <div>
                    <a href="https://github.com/Sixcha" target="_blank"><i class="fab fa-github fa-2x"></i>Github</a>
                </div>
                <p>An English Language and Literature graduate who is passionate about programming. My current skill set includes HTML, CSS(and SCSS), JavaScript, PHP, SQL and C#, and is growing every day. Currently focused on improving my C# skills which include Xamarin and Unity development. Coming from a background in literature, I sometimes do creative writing as well. My future projects include mastering ThreeJS, NodeJS and RESTful APIs.</p>
                <p>This site is a place to hold all of my personal projects: From my creative writing to the websites and video games I have made. It will be updated with more categories as my career progresses further.
                </p>
            </section>
            <div class="flexFix">
                <section id="ajax" class="column">
                    <nav>
                        <button type="button" id="WritingButton">Writing</button>
                        <!--<button type="button" id="WebsitesButton">Websites</button>
                        <button type="button" id="GamesButton">Games</button>-->
                    </nav>
                    <div class="creationFix row" id="ajax2">
                    <?php foreach ($articles as $article): ?>
                        <div class="test" >
                            <div class="link">
                                <article class="creation column articleButton" id="<?=$article["id"]?>">
                                    <h3><?= $article["title"] ?> (<?= $article["type"] ?>)</h3>
                                    <img class="creationPic <?= $article["img_position"]?>" src="../imgs/<?= $article["img"] ?>" alt="">
                                    <div class="caption"><p><?= $article["caption"] ?></p></div>
                                </article>
                            </div>
                        </div>
                    <?php endforeach; ?>
                    </div>
                </section>
            </div>
            <div class="side column">
                <a href="javascript:void(0);" onclick="showSide()" id="mobileFunc" class="langLink"><i id="faArrow" class="fas fa-angle-left fa-2x"></i></a>
                <a href="index.php" class="selectedLang langLink hidden">Eng</a>
                <a href="index.php?page=home&lang=fr" class="langLink hidden">Fr</a>
                <a href="#" class="langLink hidden">Back to Top</a>
                <!--<a href="index.php?page=about&lang=eng" class="langLink hidden">About</a>-->
            </div>
        </div>
    </main>
    <footer>
        
    </footer>
    <script src="js/script.js"></script>
    <script src="../js/utilities.js"></script>
</body>
</html>